/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205743;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class WarriorTest{
    @Test
    void attackWithWeponSkillTest() {
    int correctDamage = 15;
    int defaultHitPoint = 100;
    Warrior demowarrior = new Warrior("デモ戦士", 100, 10);
    Enemy slime1 = new Enemy("スライムA", defaultHitPoint, 10);
    Enemy slime2 = new Enemy("スライムB", defaultHitPoint, 10);
    Enemy slime3 = new Enemy("スライムC", defaultHitPoint, 10);
    demowarrior.attackWithWeponSkill(slime1);
    demowarrior.attackWithWeponSkill(slime2);
    demowarrior.attackWithWeponSkill(slime3);
    int[] document = {slime1.getHitPoint(), slime2.getHitPoint(), slime3.getHitPoint()};
    for (int test: document){
        int result = defaultHitPoint - test;
        assertEquals(correctDamage, result);
    }
    }
}